name: BOM Interactive Proxy
slug: bom_interactive_proxy
description: Proxy for BOM interactive weather maps with full-screen rain radar map view.
version: "1.0.0"
url: https://github.com/turkflix/bom-interactive-proxy
startup: services
boot: auto
init: false
panel_icon: mdi:weather-rainy
webui: http://[HOST]:[PORT:80]/
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
ports:
  80/tcp: 8083
ports_description:
  80/tcp: BOM map proxy HTTP port
options: {}
schema: {}
